-- MySQL Script generated by MySQL Workbench
-- Wed Jun  5 09:28:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;


-- -----------------------------------------------------
-- Table `mydb`.`registro-usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`registro-usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(100) NOT NULL,
  `tipo_id` VARCHAR(45) NOT NULL,
  `departamento` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(20) NOT NULL,
  `rol` VARCHAR(20) NOT NULL,
  `correo` VARCHAR(123) NOT NULL,
  `telefono` INT(10) NOT NULL,
  PRIMARY KEY (`id`, `rol`))
ENGINE = MEMORY
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`gestion-rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gestion-rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT)
ENGINE = MEMORY
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `id` ON `mydb`.`gestion-rol` (`id_rol` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
